#!/usr/bin/env bash
#
# docs_smoke.sh — compile-and-run smoke test for the C sample embedded in
# ../STATIC_MEMORY.md ("## Top-level usage"), so that snippet cannot silently
# rot out of sync with the real aec_get_mem_size()/aec_init()/aec_destroy()
# signatures declared in ../include/aec.h (this bit us before: the doc used
# to show a stale 4-arg `aec_init(&aec, pool, pool_bytes, &cfg)` while the
# real API is 3-arg and pointer-returning — `Aec* aec_init(void* mem,
# size_t mem_size, const AecConfig* cfg)`).
#
# How it works:
#   STATIC_MEMORY.md wraps the sample in HTML comment markers:
#       <!-- docs-smoke:begin -->
#       ```c
#       ... the sample ...
#       ```
#       <!-- docs-smoke:end -->
#   This script greps out everything between the markers, strips the ```c
#   fence lines, drops it into a generated main() that supplies the small
#   helpers the doc snippet assumes exist (read_block/write_block), compiles
#   it against the real AEC sources + the shared audio_common archive (the
#   same gcc invocation documented in STATIC_MEMORY.md's "Verification"
#   section), and runs the result on ~1 second of silence.
#
# This is a documentation regression check, not part of `make`/CI wiring —
# no Makefile is touched or required. Run it by hand:
#
#   cd c_impl/test && ./docs_smoke.sh              # BACKEND=ne10 (default)
#   cd c_impl/test && BACKEND=kiss ./docs_smoke.sh  # portable reference path
#
# (or from anywhere: /path/to/c_impl/test/docs_smoke.sh — paths are resolved
# relative to this script's own location, not $PWD).
#
# Exit code 0 + "docs_smoke: PASS" on stdout means the doc sample still
# compiles clean against the current aec.h and runs to completion without
# aec_init() returning NULL or crashing.

set -euo pipefail

BACKEND="${BACKEND:-ne10}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
C_IMPL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
AC_DIR="$(cd "$C_IMPL_DIR/../../audio_common" && pwd)"
DOC="$C_IMPL_DIR/STATIC_MEMORY.md"

if [ ! -f "$DOC" ]; then
    echo "docs_smoke: FAIL — cannot find $DOC" >&2
    exit 1
fi

WORK="$(mktemp -d "${TMPDIR:-/tmp}/docs_smoke.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

echo "== docs_smoke: extracting '## Top-level usage' sample from $DOC =="

# Pull everything between the markers, then keep only the lines strictly
# between the ```c fence and the closing ``` fence (i.e. drop the fences
# themselves so what's left is pure C).
awk '/<!-- docs-smoke:begin -->/{flag=1; next} /<!-- docs-smoke:end -->/{flag=0} flag' "$DOC" \
    | awk '/^```c$/{incode=1; next} /^```$/{incode=0; next} incode' \
    > "$WORK/sample.c.inc"

if [ ! -s "$WORK/sample.c.inc" ]; then
    echo "docs_smoke: FAIL — no sample extracted between docs-smoke markers in $DOC" >&2
    echo "            (expected '<!-- docs-smoke:begin -->' / '<!-- docs-smoke:end -->' around a \`\`\`c block)" >&2
    exit 1
fi

echo "== docs_smoke: extracted sample =="
cat "$WORK/sample.c.inc"
echo "== end sample =="

cat > "$WORK/docs_smoke_main.c" <<'HEADER_EOF'
/* Auto-generated by docs_smoke.sh — do not edit by hand.
 * Wraps the STATIC_MEMORY.md "Top-level usage" sample in a runnable main()
 * fed ~1 second of silence, so the doc sample is compiled and executed as
 * part of every review pass instead of just eyeballed. */
#include "aec.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int g_frames_left;

/* Stand-ins for the doc's implied "your own audio I/O" callbacks. */
static int read_block(float* mic, float* ref, int hop) {
    if (g_frames_left <= 0) return 0;
    memset(mic, 0, sizeof(float) * (size_t)hop);
    memset(ref, 0, sizeof(float) * (size_t)hop);
    g_frames_left--;
    return 1;
}

static void write_block(const float* out, int hop) {
    (void)out; (void)hop; /* silence in, silence out -- nothing to check here */
}

int main(void) {
    const int sample_rate = 16000;
    g_frames_left = sample_rate / 160; /* ~1s of silence at hop=160 @ 16 kHz */

HEADER_EOF

cat "$WORK/sample.c.inc" >> "$WORK/docs_smoke_main.c"

cat >> "$WORK/docs_smoke_main.c" <<'FOOTER_EOF'

    printf("docs_smoke: PASS (%d frames processed, hop=%d)\n",
           sample_rate / 160, hop);
    return 0;
}
FOOTER_EOF

echo "== docs_smoke: building audio_common (BACKEND=$BACKEND) =="
make -C "$AC_DIR" BACKEND="$BACKEND" lib

# Resolve the exact archive path for THIS build (audio_common's bin/ is
# keyed bin/<backend>-<config-hash>/, not a flat
# bin/$BACKEND/ -- print-lib-path is queried with the SAME BACKEND= this
# script's own `make -C "$AC_DIR" BACKEND="$BACKEND" lib` line just used, so
# the two can never point at different configs).
AC_LIB_PATH="$(make -s -C "$AC_DIR" BACKEND="$BACKEND" print-lib-path)"

echo "== docs_smoke: compiling extracted sample against aec.h + libaudio_common ($BACKEND) =="
# Compile as C with the C driver, then LINK with the C++ driver for ne10:
# the NE10 archive carries one C++ TU, and the C++
# driver supplies the correct C++ runtime itself (libc++ on macOS/clang,
# libstdc++ on GNU/Linux gcc) -- no hardcoded -lc++ (a macOS-ism that fails
# to link on GNU/Linux), mirroring the Makefiles' own LINK=$(CXX) pattern.
LINK_DRV=gcc
if [ "$BACKEND" = "ne10" ]; then
    LINK_DRV=c++
fi

SOURCES=("$WORK/docs_smoke_main.c")
while IFS= read -r -d '' src; do
    SOURCES+=("$src")
done < <(find "$C_IMPL_DIR/src" -name '*.c' -print0)

OBJ_LIST=()
i=0
for src in "${SOURCES[@]}"; do
    obj="$WORK/docs_smoke_obj_$i.o"
    gcc -O2 -ffp-contract=off -std=gnu99 \
        -I"$C_IMPL_DIR/include" -I"$C_IMPL_DIR/example" -I"$AC_DIR/include" \
        -c "$src" -o "$obj"
    OBJ_LIST+=("$obj")
    i=$((i + 1))
done

"$LINK_DRV" "${OBJ_LIST[@]}" "$AC_LIB_PATH" -lm -o "$WORK/docs_smoke_bin"

echo "== docs_smoke: running (BACKEND=$BACKEND) =="
"$WORK/docs_smoke_bin"
