"""Generate c_impl/include/aec3_balanced_config.h — the baked v3.22 balanced
AEC3 sub-module construction config.

The orchestrator builds AecState / ResidualEchoEstimator / SuppressionGain /
StationarityEstimator with a large set of derived constants (hz_to_bin,
fft_density_scale, wall-clock-rescaled CNG/ratchet constants, per-bin tuning
interpolation). Rather than re-derive all of that in C (and risk a 1-ULP drift),
we capture the LIVE balanced instance's exact values once and emit them as C
literals. aec_create() then bakes them straight into the sub-module init calls,
mirroring c_impl/test/parity_aec3_post_run.c.

gentle / aggressive differ from balanced ONLY in split_floor_far_active_db
(gentle -20 / balanced -28 / aggressive -38), applied at runtime in
aec_config_from_preset — so only the balanced base is baked here.

Run: python3 python/diag/gen_aec_balanced_config_h.py
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

from modules.config import AecConfig                          # noqa: E402
from modules.orchestrator import AEC                          # noqa: E402
from gen_aec3_post_run_golden import (                        # noqa: E402
    capture_sg_config, capture_state_config, capture_ree_config)

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, 'c_impl', 'include', 'aec3_balanced_config.h')

SR = 16000
FL = 832


def f64(x):
    return '%.17g' % float(x)


def fl(x):
    """Format a float32 as a valid C float literal (always has a decimal
    point / exponent so it never degenerates to e.g. `0f`)."""
    s = '%.9g' % float(np.float32(x))
    if ('.' not in s) and ('e' not in s) and ('E' not in s) \
            and ('inf' not in s) and ('nan' not in s):
        s += '.0'
    return s + 'f'


def emit_array(name, arr):
    vals = ', '.join(fl(v) for v in arr)
    return 'static const float %s[%d] = { %s };\n' % (name, len(arr), vals)


def main():
    cfg = AecConfig.from_preset('balanced', sample_rate=SR, filter_length=FL)
    np.random.seed(0)
    aec = AEC(cfg)
    f = aec.filter
    sg = capture_sg_config(aec._aec3_sg)
    st = capture_state_config(aec._aec3_state)
    rc = capture_ree_config(aec._aec3_ree)

    tdf = f.get_time_domain_filter()
    filter_taps_size = int(len(tdf))

    lines = []
    w = lines.append
    w('/* aec3_balanced_config.h — AUTO-GENERATED by\n')
    w(' * python/diag/gen_aec_balanced_config_h.py. DO NOT EDIT BY HAND.\n')
    w(' *\n')
    w(' * Baked v3.22 BALANCED AEC3 sub-module construction config, captured\n')
    w(' * from the live Python balanced instance (bit-exact source of truth).\n')
    w(' */\n')
    w('#ifndef AEC3_BALANCED_CONFIG_H\n#define AEC3_BALANCED_CONFIG_H\n\n')

    # ── geometry ──
    w('/* geometry */\n')
    w('#define AEC3B_N_BINS        %d\n' % int(f.n_freqs))
    w('#define AEC3B_FFT_SIZE      %d\n' % int(f.fft_size))
    w('#define AEC3B_BLOCK_SIZE    %d\n' % int(f.block_size))
    w('#define AEC3B_HOP_SIZE      %d\n' % int(f.hop_size))
    w('#define AEC3B_N_PARTITIONS  %d\n' % int(f.n_partitions))
    w('#define AEC3B_FILTER_TAPS_SIZE %d\n\n' % filter_taps_size)

    # ── driver flags ──
    w('/* aec3_post driver flags */\n')
    w('#define AEC3B_ERLE_COH_GATE_ENABLED  %d\n'
      % int(bool(cfg.erle_coh_gate_enabled)))
    w('#define AEC3B_COH_GAIN_FLOOR_ENABLED %d\n'
      % int(bool(getattr(cfg, 'coh_gain_floor_enabled', False))))
    w('#define AEC3B_COHXD_FLOOR_RELEASE_ENABLED %d\n'
      % int(bool(getattr(cfg, 'cohxd_floor_release_enabled', False))))
    w('#define AEC3B_ERLE_WINDOWED_CAPTURE_PSD %d\n'
      % int(bool(getattr(cfg, 'erle_windowed_capture_psd', False))))
    w('#define AEC3B_ERLE_RENDER_X2_PSD_SCALE %d\n'
      % int(bool(getattr(cfg, 'erle_render_x2_psd_scale', False))))
    w('#define AEC3B_OUTPUT_CAPTURE_WHEN_LINEAR_UNUSABLE %d\n'
      % int(bool(getattr(cfg, 'output_capture_when_linear_unusable', False))))
    w('#define AEC3B_ENABLE_CNG %d\n'
      % int(bool(cfg.enable_cng)))
    w('#define AEC3B_USE_STATIONARITY_PROPERTIES %d\n'
      % int(bool(aec._aec3_sg_config.echo_audibility.use_stationarity_properties)))
    w('#define AEC3B_STATIONARITY_CONVERGE_HOPS %d\n'
      % int(aec._aec3_stationarity_converge_hops))
    w('#define AEC3B_ACTIVE_RENDER_THRESHOLD (%s)\n\n' % f64(5.96e-4))

    # ── CNG constants ──
    w('/* CNG wall-clock-rescaled constants */\n')
    w('#define AEC3B_CNG_Y2_ALPHA (%s)\n' % f64(aec._aec3_cng_y2_alpha))
    w('#define AEC3B_CNG_N2_TRACK_FRESHNESS (%s)\n'
      % f64(aec._aec3_cng_n2_track_freshness))
    w('#define AEC3B_CNG_N2_TRACK_RETENTION (%s)\n'
      % f64(aec._aec3_cng_n2_track_retention))
    w('#define AEC3B_CNG_N2_SLOW_UP (%s)\n' % f64(aec._aec3_cng_n2_slow_up))
    w('#define AEC3B_CNG_N2_INITIAL_ALPHA (%s)\n'
      % f64(aec._aec3_cng_n2_initial_alpha))
    w('#define AEC3B_CNG_N2_UPDATE_ONSET_HOPS %d\n'
      % int(aec._aec3_cng_n2_update_onset_hops))
    w('#define AEC3B_CNG_N2_INITIAL_DURATION_HOPS %d\n'
      % int(aec._aec3_cng_n2_initial_duration_hops))
    w('#define AEC3B_NOISE_FLOOR_INT16SQ (%s)\n'
      % f64(aec._aec3_noise_floor_int16sq))
    w('#define AEC3B_ERLE_COH_GATE_ALPHA (%s)\n' % f64(cfg.erle_coh_gate_alpha))
    w('#define AEC3B_ERLE_COH_GATE_THRESHOLD (%s)\n\n'
      % f64(cfg.erle_coh_gate_threshold))

    # ── synth window + sqrt2 sin LUT ──
    w(emit_array('AEC3B_SYNTH_WINDOW',
                 np.asarray(aec._aec3_synth_window, np.float32)))
    w(emit_array('AEC3B_SQRT2_SIN_LUT',
                 np.asarray(aec._aec3_sqrt2_sin_lut, np.float32)))
    w('\n')

    # ── AecState config ──
    w('/* AecState config */\n')
    w('#define AEC3B_ST_NUM_CAPTURE_CHANNELS %d\n' % int(st['num_capture_channels']))
    w('#define AEC3B_ST_ENABLE_FILTER_ANALYZER %d\n' % int(st['enable_filter_analyzer']))
    w('#define AEC3B_ST_ERLE_STARTUP_HOPS %d\n' % int(st['erle_startup_hops']))
    w('#define AEC3B_ST_ERL_STARTUP_HOPS %d\n' % int(st['erl_startup_hops']))
    w('#define AEC3B_ST_ECHO_CAN_SATURATE %d\n' % int(st['echo_can_saturate']))
    w('#define AEC3B_ST_USE_LINEAR_FILTER %d\n' % int(st['use_linear_filter']))
    w('#define AEC3B_ST_CONSERVATIVE_INITIAL_PHASE %d\n' % int(st['conservative_initial_phase']))
    w('#define AEC3B_ST_DELAY_HEADROOM_SAMPLES %d\n' % int(st['delay_headroom_samples']))
    w('#define AEC3B_ST_INITIAL_STATE_SECONDS (%s)\n' % f64(st['initial_state_seconds']))
    w('#define AEC3B_ST_ERLE_MIN (%s)\n' % f64(st['erle_min']))
    w('#define AEC3B_ST_ERLE_MAX_L (%s)\n' % f64(st['erle_max_l']))
    w('#define AEC3B_ST_ERLE_MAX_H (%s)\n\n' % f64(st['erle_max_h']))

    # ── ResidualEchoEstimator config ──
    w('/* ResidualEchoEstimator config */\n')
    w('#define AEC3B_REE_HOP_SIZE %d\n' % int(rc['hop_size']))
    w('#define AEC3B_REE_MODEL_REVERB_IN_NL %d\n' % int(rc['model_reverb_in_nl']))
    w('#define AEC3B_REE_ERLE_ONSET_COMP %d\n' % int(rc['erle_onset_comp']))
    w('#define AEC3B_REE_REVERB_ENABLED %d\n' % int(rc['reverb_enabled']))
    w('#define AEC3B_REE_USE_AEC3_RESIDUAL_NOISE_GATE %d\n' % int(rc['use_aec3_residual_noise_gate']))
    w('#define AEC3B_REE_USE_AEC3_ECHO_GEN_WINDOW %d\n' % int(rc['use_aec3_echo_gen_window']))
    w('#define AEC3B_REE_NL_R2_ENABLED %d\n' % int(rc['nl_r2_enabled']))
    w('#define AEC3B_REE_NOISE_FLOOR_HOLD_HOPS %d\n' % int(rc['noise_floor_hold_hops']))
    w('#define AEC3B_REE_USE_FREQ_RESPONSE %d\n' % int(rc['use_freq_response']))
    w('#define AEC3B_REE_REVERB_USE_CONSERVATIVE %d\n' % int(rc['reverb_use_conservative']))
    w('#define AEC3B_REE_MIN_NOISE_FLOOR_POWER (%s)\n' % f64(rc['min_noise_floor_power']))
    w('#define AEC3B_REE_NOISE_GATE_POWER_LEGACY (%s)\n' % f64(rc['noise_gate_power_legacy']))
    w('#define AEC3B_REE_NOISE_GATE_SLOPE (%s)\n' % f64(rc['noise_gate_slope']))
    w('#define AEC3B_REE_STATIONARY_GATE_SLOPE (%s)\n' % f64(rc['stationary_gate_slope']))
    w('#define AEC3B_REE_DEFAULT_GAIN (%s)\n' % f64(rc['default_gain']))
    w('#define AEC3B_REE_TM_GAIN (%s)\n' % f64(rc['tm_gain']))
    w('#define AEC3B_REE_REVERB_DECAY (%s)\n' % f64(rc['reverb_decay']))
    w('#define AEC3B_REE_REVERB_MILD_SCALE (%s)\n' % f64(rc['reverb_mild_scale']))
    w('#define AEC3B_REE_REVERB_TAIL_STRENGTH (%s)\n' % f64(rc['reverb_tail_strength']))
    w('#define AEC3B_REE_NL_R2_ALPHA (%s)\n' % f64(rc['nl_r2_alpha']))
    w('#define AEC3B_REE_NL_NORM_POWER (%s)\n' % f64(rc['nl_norm_power']))
    w('#define AEC3B_REE_RESIDUAL_NOISE_GATE_POWER (%s)\n' % f64(rc['residual_noise_gate_power']))
    w('#define AEC3B_REE_REVERB_SMOOTHING_BASE (%s)\n\n' % f64(rc['reverb_smoothing_base']))

    # ── SuppressionGain config ──
    w('/* SuppressionGain config (split_floor_far_active is the preset axis,\n')
    w(' * recomputed at runtime; the baked value is the balanced -28 dB one). */\n')
    w('#define AEC3B_SG_SPLIT_FLOOR_FAR_ACTIVE (%s)\n' % f64(sg['split_floor_far_active']))
    w('#define AEC3B_SG_SPLIT_FLOOR_FAR_SILENT (%s)\n' % f64(sg['split_floor_far_silent']))
    w('#define AEC3B_SG_SPLIT_FLOOR_LATCH_POWER (%s)\n' % f64(sg['split_floor_latch_power']))
    w('#define AEC3B_SG_LOW_RENDER_THRESHOLD (%s)\n' % f64(sg['low_render_threshold']))
    w('#define AEC3B_SG_MAX_INC (%s)\n' % f64(sg['max_inc']))
    w('#define AEC3B_SG_MAX_DEC_LF (%s)\n' % f64(sg['max_dec_lf']))
    w('#define AEC3B_SG_SOFT_BLEND_ENABLED %d\n' % int(sg['soft_blend_enabled']))
    w('#define AEC3B_SG_SOFT_BLEND_PER_BIN %d\n' % int(sg['soft_blend_per_bin']))
    w('#define AEC3B_SG_SOFT_BLEND_ENR_THR (%s)\n' % f64(sg['soft_blend_enr_thr']))
    w('#define AEC3B_SG_SOFT_BLEND_SOFTNESS (%s)\n' % f64(sg['soft_blend_softness']))
    w('#define AEC3B_SG_LAST_LF_BAND %d\n' % int(sg['last_lf_band']))
    w('#define AEC3B_SG_FIRST_HF_BAND %d\n' % int(sg['first_hf_band']))
    w('#define AEC3B_SG_LAST_LF_SMOOTHING_BAND %d\n' % int(sg['last_lf_smoothing_band']))
    w('#define AEC3B_SG_LAST_PERMANENT %d\n' % int(sg['last_permanent']))
    w('#define AEC3B_SG_LF_SMOOTHING_INITIAL %d\n' % int(sg['lf_smoothing_initial']))
    w('#define AEC3B_SG_DNE_LF_END %d\n' % int(sg['dne_lf_end']))
    w('#define AEC3B_SG_TRIGGER_THRESHOLD_HOPS %d\n' % int(sg['trigger_threshold_hops']))
    w('#define AEC3B_SG_HOLD_DURATION_HOPS %d\n' % int(sg['hold_duration_hops']))
    w('#define AEC3B_SG_NEAREND_SMOOTHER_N %d\n' % int(sg['nearend_smoother_n']))
    w('#define AEC3B_SG_AUD_LF_END_BIN %d\n' % int(sg['aud_lf_end_bin']))
    w('#define AEC3B_SG_AUD_MF_END_BIN %d\n' % int(sg['aud_mf_end_bin']))
    w('#define AEC3B_SG_FLOOR_POWER (%s)\n' % f64(sg['floor_power']))
    w('#define AEC3B_SG_AUD_THR_LF (%s)\n' % f64(sg['aud_thr_lf']))
    w('#define AEC3B_SG_AUD_THR_MF (%s)\n' % f64(sg['aud_thr_mf']))
    w('#define AEC3B_SG_AUD_THR_HF (%s)\n' % f64(sg['aud_thr_hf']))
    w('#define AEC3B_SG_LOW_RENDER_LIMIT (%s)\n' % f64(sg['low_render_limit']))
    w('#define AEC3B_SG_NORMAL_RENDER_LIMIT (%s)\n' % f64(sg['normal_render_limit']))
    w('#define AEC3B_SG_HF_LGB %d\n' % int(sg['hf_lgb']))
    w('#define AEC3B_SG_HF_BIQ %d\n' % int(sg['hf_biq']))
    w('#define AEC3B_SG_CONSERVATIVE_HF %d\n' % int(sg['conservative_hf']))
    w('#define AEC3B_SG_DNE_ENR_THRESHOLD (%s)\n' % f64(sg['dne_enr_threshold']))
    w('#define AEC3B_SG_DNE_ENR_EXIT_THRESHOLD (%s)\n' % f64(sg['dne_enr_exit_threshold']))
    w('#define AEC3B_SG_DNE_SNR_THRESHOLD (%s)\n' % f64(sg['dne_snr_threshold']))
    w('#define AEC3B_SG_DNE_USE_DURING_INITIAL_PHASE %d\n' % int(sg['dne_use_during_initial_phase']))
    w('#define AEC3B_SG_DNE_USE_UNBOUNDED_ECHO %d\n' % int(sg['dne_use_unbounded_echo']))
    w('#define AEC3B_SG_DNE_LF_ENDPOINT_BIN %d\n\n' % int(sg['dne_lf_endpoint_bin']))

    # ── per-bin tuning arrays ──
    w('/* SuppressionGain per-bin tuning arrays (LF/HF interpolated). */\n')
    w(emit_array('AEC3B_SG_NEAREND_ENR_TR', sg['nearend_enr_tr']))
    w(emit_array('AEC3B_SG_NEAREND_ENR_SU', sg['nearend_enr_su']))
    w(emit_array('AEC3B_SG_NEAREND_EMR_TR', sg['nearend_emr_tr']))
    w(emit_array('AEC3B_SG_NORMAL_ENR_TR', sg['normal_enr_tr']))
    w(emit_array('AEC3B_SG_NORMAL_ENR_SU', sg['normal_enr_su']))
    w(emit_array('AEC3B_SG_NORMAL_EMR_TR', sg['normal_emr_tr']))
    w('\n#endif /* AEC3_BALANCED_CONFIG_H */\n')

    with open(OUT, 'w') as fh:
        fh.writelines(lines)
    print('wrote %s (%d lines, n_bins=%d filter_taps=%d)'
          % (OUT, len(lines), int(f.n_freqs), filter_taps_size))


if __name__ == '__main__':
    main()
